export default function RefundsPage() {
  return (
    <div className="min-h-[calc(100vh-3.5rem)] bg-white">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="mb-2 text-3xl font-bold text-neutral-900">Terms of Sale &amp; Refund Policy</h1>
        <p className="mb-8 text-sm text-neutral-400">Last updated: March 18, 2026</p>
        <div className="space-y-8 text-neutral-600">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">1. Seller</h2>
          <p>
            KLIKANGO (SAS)
            <br />
            16 Avenue Sainte-Marie, 94160 Saint-Mandé, France
            <br />
            SIREN: 948 465 331 — VAT: FR42948465331
            <br />
            contact@manyminds.io
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">2. Products and Prices</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>All prices are in USD and exclude applicable taxes</li>
            <li>Subscriptions are billed monthly or annually depending on your chosen plan</li>
            <li>Top-up credit packs are one-time purchases</li>
            <li>Prices may change with 30 days advance notice by email</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">3. Payment</h2>
          <p>
            Payments are processed securely by Stripe. We accept major credit and debit cards. By
            providing payment information, you authorize KLIKANGO to charge your payment method for
            the selected plan.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">4. Subscriptions</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>Subscriptions renew automatically at the end of each billing period</li>
            <li>You can cancel at any time from your account settings</li>
            <li>Cancellation takes effect at the end of the current billing period</li>
            <li>No partial refunds for unused time in a billing period</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">
            5. Right of Withdrawal (EU Consumers)
          </h2>
          <p>
            Under EU consumer law, you have the right to withdraw from a subscription within 14 days
            of purchase without giving any reason, provided you have not used the service. To
            exercise this right, contact us at{' '}
            <a href="mailto:billing@manyminds.io" className="text-violet-600 hover:underline">
              billing@manyminds.io
            </a>{' '}
            within 14 days of your purchase.
          </p>
          <p className="mt-2">
            By using ManyMinds immediately after purchase, you expressly waive your right of
            withdrawal for the consumed credits.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">6. Refunds</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>
              New subscribers may request a full refund within 7 days of their first payment if they
              are not satisfied
            </li>
            <li>Top-up credit packs are non-refundable once credits have been used</li>
            <li>Annual plan refunds are prorated for unused months if requested within 30 days</li>
            <li>
              Refund requests:{' '}
              <a href="mailto:billing@manyminds.io" className="text-violet-600 hover:underline">
                billing@manyminds.io
              </a>
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">7. Failed Payments</h2>
          <p>
            If a payment fails, we will notify you by email and retry the charge. If payment remains
            unsuccessful after 3 attempts, your account will be downgraded to the Free plan until
            payment is resolved.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">8. Invoices</h2>
          <p>
            Invoices are automatically generated by Stripe and sent to your registered email address
            after each payment.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">9. Governing Law</h2>
          <p>
            These Terms of Sale are governed by French law. Consumer disputes may be referred to the
            European Online Dispute Resolution platform:{' '}
            <a
              href="https://ec.europa.eu/consumers/odr"
              target="_blank"
              rel="noreferrer"
              className="text-violet-600 hover:underline"
            >
              ec.europa.eu/consumers/odr
            </a>
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-neutral-900">10. Contact</h2>
          <p>billing@manyminds.io</p>
        </section>
        </div>
      </div>
    </div>
  );
}

